#!/bin/bash
set -e;

rename='true';
threads='6';
inflags=();
outflags=();
decoder='';
encoder='h264_videotoolbox';
out='';
res='';

while [ "$#" -gt '0' ] && [ "${1:0:1}" == '-' ]; do
    case "$1" in
        '-c'|'--copy')
            encoder='copy';
            ;;
        '-d'|'--down')
            res='360';
            ;;
        '-h'|'--hevc')
#            encoder='hevc_videotoolbox';
            encoder='libx265';
            ;;
        '-n'|'--nores')
            rename='false';
            ;;
        '-o'*)
            out="${1:2}";
            ;;
        '-r'*)
            res="${1:2}";
            ;;
        '-s'|'--slow')
            outflags+=('-preset' 'veryslow');
            ;;
        '-t'*)
            threads="${1:2}";
            ;;
        *)
            echo "Unrecognised option: $1";
            exit 1;
            ;;
    esac;
    shift;
done;
if ! [ -z "$decoder" ]; then
    inflags+=('-c:v' "$decoder");
fi;
if ! [ -z "$encoder" ]; then
    outflags+=('-c:v' "$encoder");
fi;
if ! [ -z "$res" ]; then
    outflags+=('-vf' "scale=-2:$res");
fi;

if [ "$#" == 0 ]; then
    echo 'Usage:';
    echo "    $(basename "$0") [options] file1 [file2 [...]]";
    echo 'Options:';
    echo '    -c --copy   Copy video codec';
    echo '    -d --down   Scale down to 360p';
    echo '    -h --hevc   HEVC';
    echo "    -n --nores  Don't put resolution in file name";
    echo '    -o<path>    Write to path/';
    echo '    -r<res>     Scale to resolution';
    echo '    -s --slow   Slower, but better compression';
    echo '    -t<X>       Use X threads';
    exit 1;
fi;

while [ "$1" != '' ]; do
    if "$rename"; then
        if [ -z "$res" ]; then
            if hash ffratio 2>/dev/null; then
                r="$(ffratio "$1" | sed -E 's/^[0-9]+x([0-9]+)$/\1/g')";
            else
                r="$(ffprobe "$1" 2>&1 | grep -E 'Video:.* [0-9]+x[0-9]+[ ,]' | head -1 | sed -E 's/^.* [0-9]+x([0-9]+)[ ,].*$/\1/g';)";
            fi;
            case "$r" in
                ''|*[!0-9]*)
                    echo "Cannot determine resolution of $1";
                    exit 1;
                    ;;
            esac;
        else
            r="$res";
        fi;
        target="$(echo "$1" | sed -E 's/\.[^\.]+$/.'"$r"'.mkv/g')";
    else
        target="$(echo "$1" | sed -E 's/\.[^\.]+$/.mkv/g')";
    fi;
    if ! [ -z "$out" ]; then
        target="$out/$(basename "$target")";
    fi;
    ffmpeg "${inflags[@]}" -i "$1" -sn -threads "$threads" "${outflags[@]}" "$target";
    if hash xattrcopy 2>/dev/null; then
        xattrcopy "$1" "$target";
    fi;
    shift;
done;
